name: Building

on:
  push:
    tags:
      - '*inet'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Compile source
        run: |
          mkdir -p build
          gcc src/footfetch.c -o build/footfetch

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Footfetch ${{ github.ref_name }}"
          body: |
            ## Footfetch ${{ github.ref_name }}

            * [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)
            * [Full ChangeLog](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }})
            
            ---
          generate_release_notes: true
          files: build/footfetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}