name: Rust CI & AUR Release

on:
  push:
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo Check
        run: cargo check
      - name: Run Tests
        run: cargo test

  deploy-aur:
    name: Deploy to AUR
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish AUR package
        uses: KSX-Zeal/aur-release@main
        with:
          pkgname: footfetch-git
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"

  github-release:
    name: GitHub Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: cargo build --release --locked
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/footfetch
          body: |
            ## Footfetch ${{ github.ref_name }}

            * [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)
            
            ---
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
